### ISSUE TITLE
Widget Stacking

### ISSUE THREAD

**Issue by Poikilos** [octacian/hudplus#1]
Hi octacian,

I found your mod while looking to alternatives to hud_hunger, which seems to have some deficiencies. I suggest that since you are in the early stages you keep something in mind that could make your mod better than the hud in hud_hunger: widget stacking. In hud (including tenplus1's updated version in his fork of hud_hunger), when more meters are added they may overlap (sprint overlaps armor in current version). A better solution would be to just give an alignment (such as topleft, bottomleft, bottomright, bottomleft--maybe even topcenter, bottomcenter) for each meter, then keep track of where they are, so if another meter is added, it is automatically placed in an empty spot. You could have spacing variables for x and y, and an object for each position (tl, bl, br, bl) and each of those objects could store a list, and you could use the last one in the list's location with those spacing variables. Eventually you could have the ability either a graphical heart bar or a text label which could be added and removed (such as for mods that want to display timers or game/quest state messages for all players or certain players permanently until the mod wants to remove the label) and alignment could be reprocessed at that time in case any widgets are higher in the list.

**Comment by octacian** [comment]
This is an interesting idea. I had not considered it originally, though I think it would definitely be worth some thought. These are my current thoughts.

Implement the above functionality (though I do have to do research as to whether all is possible - if anything would be hard it's aligning other than from the center), with a setting for HUDs to disable auto positioning (e.g. `auto_position = false`). Again, I still have to give this some more thought, but overall, great idea!

**Comment by octacian** [comment]
Would you mind reopening this issue in https://github.com/octacian/hudlib? I've moved the library portion of this mod there and will soon be ready to begin developing parts of this with parent-child constraints.

**Comment by Poikilos** [comment]
Ok here it is: [https://github.com/octacian/hudlib/issues/1](https://github.com/octacian/hudlib/issues/1)

**Comment by octacian** [comment]
Thanks!
